name: dbt CI

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: [ main ]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ../.dbt
      DBT_PROFILE: dummy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.11.2 dbt-duckdb

      - name: Debug dbt
        run: |
          cd dbt_ci
          pwd
          ls -la
          ls -la ../.dbt
          cat ../.dbt/profiles.yml
          dbt debug

      - name: Extract ticket id
        run: |
          BRANCH="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
          echo "Branch: $BRANCH"

          TICKET=$(echo "$BRANCH" | grep -o 'EDM-[0-9]\+' || true)

          if [ -z "$TICKET" ]; then
            echo "No ticket found in branch, skipping ticket-based validation"
          else
            echo "Ticket detected: $TICKET"
          fi

          echo "TICKET=$TICKET" >> $GITHUB_ENV

      - name: Run dbt
        run: |
          cd dbt_ci
          dbt run

      - name: Run show.py
        run: |
          set +e
          python show.py "$TICKET_ID" > show_output.txt 2>&1
          SHOW_EXIT_CODE=$?
          echo "SHOW_EXIT_CODE=$SHOW_EXIT_CODE" >> $GITHUB_ENV

          {
            echo "SHOW_OUTPUT<<EOF"
            cat show_output.txt
            echo "EOF"
          } >> $GITHUB_ENV