name: dbt CI (no DB)

on:
  pull_request_target:
    branches: [ main ]

jobs:
  dbt-compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create dummy profiles.yml
      run: |
        mkdir -p ~/.dbt
        cat <<EOF > ~/.dbt/profiles.yml
        dummy:
          target: dev
          outputs:
            dev:
              type: duckdb
              path: ":memory:"
        EOF

    - name: dbt compile (NO DB)
      run: |
        cd dbt_ci
        dbt compile --no-version-check

    - name: Validate SQL
      run: |
        python show.py marts/sample_model
